[project]
name = "acsr"
version = "0.1.0"
description = ""
authors = [
    {name = "Boubacar Sow"}
]
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "numpy (==2.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
