_wandb:
    value:
        cli_version: 0.19.4
        m: []
        python_version: 3.11.7
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 2
                - 16
                - 23
                - 55
            "4": 3.11.7
            "5": 0.19.4
            "8":
                - 5
            "12": 0.19.4
            "13": linux-x86_64
batch_size:
    value: 16
device:
    value: cuda
epochs:
    value: 500
hidden_dim_features:
    value: 128
hidden_dim_fusion:
    value: 256
learning_rate:
    value: 0.001
output_dim:
    value: 39
